osx_image: xcode6.4
language: c++

matrix:
  include:
    #- os: osx
    #  osx_image: xcode6.4
    - os: linux

addons:
  apt:
    packages:
      - cmake
      - xz
      - tar
      - libudev-dev
      - texinfo


script:
  - make
  - make cpack
